-- Optionnel: remplace "public" si tu utilises un schéma dédié
-- CREATE SCHEMA IF NOT EXISTS todo;
-- SET search_path TO public;

CREATE TABLE IF NOT EXISTS public.tasks(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  done BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT task_description_not_blank CHECK (btrim(description) <> '')
);
